# Generated by Django 2.2.6 on 2019-11-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('youtube_embed_text', models.TextField(max_length=2000)),
                ('no_youtube_views', models.IntegerField(default=0)),
                ('no_votes', models.IntegerField(default=0)),
                ('video_source', models.FileField(blank=True, null=True, upload_to='')),
                ('nations', models.ManyToManyField(to='home.Nation')),
            ],
        ),
    ]
