# Generated by Django 2.2.6 on 2019-11-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='nations',
            field=models.ManyToManyField(related_name='nations_list', to='home.Nation'),
        ),
    ]
