# Generated by Django 2.2.6 on 2019-11-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191118_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='nations',
            field=models.ManyToManyField(to='home.Nation'),
        ),
    ]
