# Generated by Django 2.2.6 on 2019-11-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191118_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vote_statement',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
