# Generated by Django 2.2.6 on 2019-11-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_video_vote_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='pro_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
